### ISSUE TITLE
[GS] Social Login 구현

### ISSUE THREAD

**Issue by james-majormap** [themajormap/majormap-issues#10]
## TO BE ADDED
Social Login 기능 추가

## TASKS
- [ ] Google 소셜 로그인 구현
- [ ] Facebook 소셜 로그인 구현
- [ ] User 모델에 생년월일 필드 추가
- [ ] 소셜 계정에서 생년월일 정보 받아오는 로직 구현

## SCHEDULE
* ~9월 29일 까지 완료~
* 10월 23일 까지 완료

## ISSUE CHANGE LOG
* 2020/09/25 15:30 - 최초 작성 by 제임스
* 2020/10/16 14:25 - 일정 변경 by 제임스

**Comment by james-majormap** [comment]
![image](https://user-images.githubusercontent.com/66929386/94383595-775b2800-017b-11eb-91fc-db7e8fca03f8.png)

최종적인 구현은 Niche의 UI를 따라가려고 합니다. 참고 부탁드립니다.

**Comment by seongminchoob** [comment]
social 로그인은 먼저 프론트 개발이 된 후에 추가하는게 나을 것 같습니다 ㅠㅠ
