### ISSUE TITLE
[GS] email, password 간단한 인적정보를 바탕으로 회원가입 할 수 있는 API endpoint 구성

### ISSUE THREAD

**Issue by james-majormap** [themajormap/majormap-issues#8]
## TO BE ADDED
/user/register/ 에 회원 가입 할 수 있는 endpoint 신규구성

## TASKS
- [x] /user/register/ 에 email과 password 데이터를 전송하여 새로운 User를 생성할 수 있는 endpoint 구성
- [x] email 중복 여부를 확인할 수 있는 API endpoint 구성
- [x] 테스트 케이스 작성
&emsp;* 정상적인 email / password 제출 시나리오
&emsp;* 이미 존재하는 email로 회원 가입을 시도할 때의 시나리오

## SCHEDULE
* 9월 28일 까지 완료

## ISSUE CHANGE LOG
* 2020/09/24 14:00 - 최초 작성 by 제임스
